### ISSUE TITLE
Generated assembly for Insert()

### ISSUE THREAD

**Issue by kamil-tarnas** [cavemanjaw/List#6]
https://github.com/cavemanjaw/List/commit/608ca2e390ee2d3d74165df4a4f12cce547b0a13#r42219301

Check the efficiency and generated assembly output as written in the comment from the link above.

**Comment by cavemanjaw** [comment]
template<typename Data>
void SingleLinkedList::List<Data>::Insert(Data data)
{
	Node<Data>** nodePtr = &head;

	//Traverse to the nearest nullptr od Node* nextNode
	//Insert the value to the new node and assign pointers
	while (true)
	{
		//If head == nullptr for the first iteration
		if (*nodePtr == nullptr)
		{
			//Allocate memory to head for first iteration
			*nodePtr = new Node<Data>(data); //TODO: In case of "safe" list this would be bad
			(*nodePtr)->data = data;
			break;
		}
		else
		{
		//Assign the address of nextNode to nodePtr
			nodePtr = &((*nodePtr)->nextNode); //TODO: There is no need to reassign the pointers if nullptr has been found
		}
	}
}

**Comment by kamil-tarnas** [comment]
PrintList() was removed in 20db22891ee78fb191f55ead31471052abddfadb.

**Comment by kamil-tarnas** [comment]
Added branch with PrintList() for debugging purposes:
https://github.com/cavemanjaw/List/tree/debug

No difference in generated assembly code can be found in three implementations of Insert() - one with 'if-else', one containing just 'if' and the one with immediate 'return'.
